### ISSUE TITLE
"Error: Failed to fetch" When auth'd session apparently times out

### ISSUE THREAD

**Issue by danielopatich** [ellipticoin/ec-wallet#4]
--- refreshing, closing/reopening browser persists this error in the UI. See console/network failures below

<img width="1078" alt="Screen Shot 2020-11-30 at 10 46 55 AM" src="https://user-images.githubusercontent.com/14968390/100631142-68b6fb80-32f9-11eb-972a-f779b04f97ee.png">
<img width="1809" alt="Screen Shot 2020-11-30 at 10 47 06 AM" src="https://user-images.githubusercontent.com/14968390/100631146-69e82880-32f9-11eb-994c-3c6a9aae5c18.png">

**Comment by masonforest** [comment]
Hey @danielopatich ! 😀 

We discovered a bug and took down the network while we're fixing it.

Message from [Telegram Channel](https://t.me/ellipticoin):

> A headsup: W  found a bug could cause loss of funds. Thanks for not stealing all our money W ! Looking forward to having funding we can pay whitehat hackers bounties with someday... 
> Luckily everything in the bridge is safe.
> @WillMeister working on a fix now 🚀
> We’re gonna take the network down until we’ve got things fixed to prevent people from getting incorrect prices on their trades.
> We're planning to have everything fixed and back up and running by EOD today!

We should definitely make this error message more informative though. PRs welcome! 😀

**Comment by masonforest** [comment]
And we're back up! Let me know if you run into any issues! 😀
